<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPyz1hbt\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPyz1hbt/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPyz1hbt.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPyz1hbt\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPyz1hbt\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Pyz1hbt',
    'container.build_id' => '4e52a1d4',
    'container.build_time' => 1577728719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPyz1hbt');
